name: Build and Push to Docker Hub

on:
  push:
    branches: [ "main" ]   # adjust branch as needed

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          # Use GitHub run number as incremental tag
          IMAGE_NAME=amrh301/gitlab-sync-monitor
          IMAGE_TAG=${{ github.run_number }}

          docker build -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest .

      - name: Push Docker image
        run: |
          IMAGE_NAME=amrh301/gitlab-sync-monitor
          IMAGE_TAG=${{ github.run_number }}

          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:latest
